//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserRole
    {
        public long IdApplicationUserRole { get; set; }
        public long IdCompany { get; set; }
        public long IdApplicationRole { get; set; }
        public long IdUserApplication { get; set; }
        public bool State { get; set; }
    
        public virtual ApplicationRole ApplicationRole { get; set; }
        public virtual Company Company { get; set; }
        public virtual UserApplication UserApplication { get; set; }
    }
}
