//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateUsersGroup
    {
        public long IdAssociateUsersGroup { get; set; }
        public int IdUserGroup { get; set; }
        public long IdUserApplication { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
        public virtual UserApplication UserApplication { get; set; }
    }
}
