//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyApplication
    {
        public long IdCompanyApplication { get; set; }
        public long IdCompany { get; set; }
        public long IdApplication { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Company Company { get; set; }
    }
}
