//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.TableRef = new HashSet<TableRef>();
        }
    
        public long IdGroup { get; set; }
        public string DescriptionGroup { get; set; }
    
        public virtual ICollection<TableRef> TableRef { get; set; }
    }
}
