//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationsSettings
    {
        public long IdNotificationsSettings { get; set; }
        public long IdApplication { get; set; }
        public Nullable<long> IdUserApplication { get; set; }
        public Nullable<int> IdUserGroup { get; set; }
        public long IdNotification { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime SummaryEndDate { get; set; }
        public System.DateTime DashboardEndDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Notifications Notifications { get; set; }
        public virtual UserApplication UserApplication { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
