//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.ApplicationRole = new HashSet<ApplicationRole>();
        }
    
        public long IdRole { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<ApplicationRole> ApplicationRole { get; set; }
    }
}
