//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecurityManagmentEntities : DbContext
    {
        public SecurityManagmentEntities()
            : base("name=SecurityManagmentEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<ApplicationRole> ApplicationRole { get; set; }
        public virtual DbSet<ApplicationUserRole> ApplicationUserRole { get; set; }
        public virtual DbSet<AssociateUsersGroup> AssociateUsersGroup { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyApplication> CompanyApplication { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GUI> GUI { get; set; }
        public virtual DbSet<LastLogin> LastLogin { get; set; }
        public virtual DbSet<MenuOption> MenuOption { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<NotificationsSettings> NotificationsSettings { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SecurityGUI> SecurityGUI { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableRef> TableRef { get; set; }
        public virtual DbSet<UserApplication> UserApplication { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
    }
}
