//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRef
    {
        public TableRef()
        {
            this.Notifications = new HashSet<Notifications>();
        }
    
        public long IdReference { get; set; }
        public long IdGroup { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
    }
}
