//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplication
    {
        public UserApplication()
        {
            this.ApplicationUserRole = new HashSet<ApplicationUserRole>();
            this.AssociateUsersGroup = new HashSet<AssociateUsersGroup>();
            this.LastLogin = new HashSet<LastLogin>();
            this.NotificationsSettings = new HashSet<NotificationsSettings>();
        }
    
        public long IdUserApplication { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public Nullable<long> DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public bool State { get; set; }
        public string Email { get; set; }
        public long IdCompany { get; set; }
    
        public virtual ICollection<ApplicationUserRole> ApplicationUserRole { get; set; }
        public virtual ICollection<AssociateUsersGroup> AssociateUsersGroup { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<LastLogin> LastLogin { get; set; }
        public virtual ICollection<NotificationsSettings> NotificationsSettings { get; set; }
    }
}
