//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManagment.Data.EntityModel.SecurityManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.AssociateUsersGroup = new HashSet<AssociateUsersGroup>();
            this.NotificationsSettings = new HashSet<NotificationsSettings>();
        }
    
        public int IdUserGroup { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AssociateUsersGroup> AssociateUsersGroup { get; set; }
        public virtual ICollection<NotificationsSettings> NotificationsSettings { get; set; }
    }
}
